cluster_name: "etcd-cluster-1"
destination: stderr
listeners:
  - name: infra1
    listener_addr: "localhost:12381"
    upstream_addr: "localhost:12380"
  - name: infra2
    listener_addr: "localhost:22381"
    upstream_addr: "localhost:22380"
  - name: infra3
    listener_addr: "localhost:32381"
    upstream_addr: "localhost:32380"
